POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "sreddyj2023@gmail.com",
  "password": "password123"
}

###

POST http://localhost:3001/auth/login 
Content-Type: application/json

{
  "email": "sreddyj2023@gmail.com",
  "password": "password123"
}

###

POST http://localhost:3001/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODM4MjIyLCJpYXQiOjE3MzU4MzQ2MjIsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM0NjIyfV0sInNlc3Npb25faWQiOiIwMTdlM2ViNC1kNWEzLTRiNTgtYTIzNy1jMzgyY2VkNWRjZTQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.rGAeOmS9aLN7Lr54k_QLaTaXFJNighMb5XWKpp2Vp1Q

###

POST http://localhost:3001/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODQwNTI4LCJpYXQiOjE3MzU4MzY5MjgsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM2OTI4fV0sInNlc3Npb25faWQiOiIxMTg3MmEwMy0xOGQzLTRiMmYtOWEwYi0yNWJkZDI2YTczNzciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.J1Mf-uxyo8n6ZlFZ2x1cHUinATJeYBzySsQhjtwVzLk
Content-Type: application/json

{
  "content": "Walk the dog",
  "important": true,
  "date": "2024-12-28T09:00:00.000Z"
}

###

GET http://localhost:3001/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODQwNTI4LCJpYXQiOjE3MzU4MzY5MjgsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM2OTI4fV0sInNlc3Npb25faWQiOiIxMTg3MmEwMy0xOGQzLTRiMmYtOWEwYi0yNWJkZDI2YTczNzciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.J1Mf-uxyo8n6ZlFZ2x1cHUinATJeYBzySsQhjtwVzLk

###

GET http://localhost:3001/notes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODQwNTI4LCJpYXQiOjE3MzU4MzY5MjgsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM2OTI4fV0sInNlc3Npb25faWQiOiIxMTg3MmEwMy0xOGQzLTRiMmYtOWEwYi0yNWJkZDI2YTczNzciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.J1Mf-uxyo8n6ZlFZ2x1cHUinATJeYBzySsQhjtwVzLk

###

PUT http://localhost:3001/notes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODQwNTI4LCJpYXQiOjE3MzU4MzY5MjgsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM2OTI4fV0sInNlc3Npb25faWQiOiIxMTg3MmEwMy0xOGQzLTRiMmYtOWEwYi0yNWJkZDI2YTczNzciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.J1Mf-uxyo8n6ZlFZ2x1cHUinATJeYBzySsQhjtwVzLk
Content-Type: application/json

{
  "content": "Watch the new episode of The Mandalorian",
  "important": true,
  "date": "2024-12-28T09:00:00.000Z"
}

###

DELETE http://localhost:3001/notes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IitrVkdyYk13ODFaWFA5c2giLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3d0cXlwdW9lbnh5Z2F2eGZoc3B6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNzFjNWZlNi00NzQ4LTRlYjAtOWZiMS1lN2NlOTc0ODA5NWIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzM1ODQwNTI4LCJpYXQiOjE3MzU4MzY5MjgsImVtYWlsIjoic3JlZGR5ajIwMjNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6InNyZWRkeWoyMDIzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImE3MWM1ZmU2LTQ3NDgtNGViMC05ZmIxLWU3Y2U5NzQ4MDk1YiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzM1ODM2OTI4fV0sInNlc3Npb25faWQiOiIxMTg3MmEwMy0xOGQzLTRiMmYtOWEwYi0yNWJkZDI2YTczNzciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.J1Mf-uxyo8n6ZlFZ2x1cHUinATJeYBzySsQhjtwVzLk
